### ISSUE TITLE
Visual errors

### ISSUE THREAD

**Issue by jbenitosantoni** [RuneFarm/rune-farm#1]
I have found several errors on the latest update:

1.  Swap page is not showing background https://swap.rune.farm/#/swap
2. Twitter language menu is cut on the right https://i.imgur.com/s0Gfzyc.png
3. If we have twitter at the bottom of the menu with an icon, maybe its not neccesary to have it on More Info menu aswell, as its getting too big.
4. Language selector on menu doesnt underline when you hoover the language https://i.imgur.com/5VYyZUi.png
5. When you go to https://swap.rune.farm/#/swap **Game** tab opens in the menu instead of **swap**, same thing happens when you open https://swap.rune.farm/#/pool 
6. Lots of languages appearing when you hoover language menu from swap or pool page, those languages doesnt appear on other pages.

**Comment by binzydev** [comment]
Hey!

1. Fixed
2. Very minor but will fix
3. Agree will remove
4. Very minor but will do
5. I think thats fine for noe
6. Oh ty thats a good find

Cheers, thanks for the thorough review!
